spring:
  datasource:
    url: jdbc:mysql://localhost:2206/aed
    username: root
    password: aedlocal123@
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
