#spring:
#  profiles:
#    active: dev
#  datasource:
#    url: jdbc:mysql://localhost:2206/aed
#    username: root
#    password: aedlocal123@
#  jpa:
#    open-in-view: false
#    defer-datasource-initialization: true
#    hibernate.ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate.format_sql: true
#      hibernate.default_batch_fetch_size: 100

---
spring:
  profiles:
    active: prod
  datasource:
    url: jdbc:mysql://43.200.230.116:3306/aed
    username: aed
    password: aedlocal123@
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100